In [1]:
import pandas as pd
import numpy as np
import string

In [2]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [38]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [3]:
from gensim.models import Word2Vec
import os
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [55]:
df = pd.read_csv('../data/final_df.csv')

In [56]:
df.head()

,id,title,tags
0,1168190,The Wrecking Crew,Estranged half-brothers Jonny and James reunit...
1,840464,Greenland 2: Migration,Having found the safety of the Greenland bunke...
2,1084242,Zootopia 2,After cracking the biggest case in Zootopia's ...
3,1419406,The Shadow's Edge,Macau Police brings the tracking expert police...
4,1368166,The Housemaid,"Trying to escape her past, Millie Calloway acc..."

## Text Preprocessing

In [57]:
df.loc[:,'tags']=df['tags'].str.lower()

In [58]:
def remove_punc(text):
    for char in string.punctuation:
        text = text.replace(char,'')
    return text

In [59]:
df.loc[:,'tags']=df['tags'].apply(remove_punc)

In [60]:
def remove_stopwords(text):
    new_text = []
    text_list = text.split()
    english_stopwords = stopwords.words('english')
    for word in text_list:
        if word in english_stopwords:
            pass
        else:
            new_text.append(word)
    x = new_text[:]
    new_text.clear()
    return " ".join(x)

In [61]:
df.loc[:,'tags']=df['tags'].apply(remove_stopwords)

In [62]:
df['tags'][1]

'found safety greenland bunker comet clarke decimated earth garrity family must risk everything embark perilous journey across wasteland europe find new home adventure thriller science fiction unitedkingdom unitedstatesofamerica gerardbutler morenabaccarin romangriffindavis tommieearljenkins naturaldisaster shelter survival disaster frantic'

In [12]:
# ps = PorterStemmer()
# def stem_words(text):
#     y=[]
#     text_list = text.split()
#     for i in text_list:
#         y.append(ps.stem(i))
#     return " ".join(y)

In [13]:
# df.loc[:,'tags']=df['tags'].apply(stem_words)

In [14]:
# df['tags'][1]

## Vectorizing Data

In [63]:
movies_descriptions = df['tags'].apply(lambda x: x.split()).tolist()

In [73]:
len(movies_descriptions)

31

### TF-IDF

In [90]:
tfidf_model = TfidfVectorizer(max_features=100000,ngram_range=(1,2),min_df=2)

vectors = tfidf_model.fit_transform(df['tags']).toarray()

In [91]:
similarity_matrix = cosine_similarity(vectors)

In [92]:
similarity_matrix.shape

(7679, 7679)

In [86]:
# def recommend(index, top_n=15):
#     similarity_scores = list(enumerate(similarity_matrix[index]))
#     similarity_scores = sorted(similarity_scores, key=lambda x: x[1], reverse=True)
#     similarity_scores = similarity_scores[1:top_n+1]
    
#     recommended_indices = [i[0] for i in similarity_scores]
    
#     return df.iloc[recommended_indices]

In [96]:
def recommend(index):
    distances = similarity_matrix[index]
    movies_list = sorted(list(enumerate(distances)),reverse=True,key = lambda x:x[1])[1:11]
    recommended_index = [i[0] for i in movies_list]
    return df.iloc[recommended_index]

In [97]:
recommend(98)

,id,title,tags
129,634649,Spider-Man: No Way Home,peter parker unmasked longer able separate nor...
234,324857,Spider-Man: Into the Spider-Verse,struggling find place world juggling school fa...
475,102382,The Amazing Spider-Man 2,peter parker life busy taking bad guys spiderm...
190,315635,Spider-Man: Homecoming,following events captain america civil war pet...
383,9806,The Incredibles,bob parr given superhero days log time insuran...
316,447365,Guardians of the Galaxy Vol. 3,peter quill still reeling loss gamora must ral...
202,557,Spider-Man,bitten genetically altered spider oscorp nerdy...
288,429617,Spider-Man: Far From Home,peter parker friends go summer trip europe how...
399,969681,Spider-Man: Brand New Day,fourth installment spiderman franchise part ph...
858,38055,Megamind,megamind highly intelligent alien supervillain...

# Exporting Models

In [2]:
import pickle

In [1]:
pickle.dump(similarity_matrix,open('similarity.pkl','wb'))

NameError: name 'pickle' is not defined

In [102]:
df.to_csv("cleaned_data.csv",index=False)